Lesson_1
Ivan-Sizyh/TestGuru pull request #1
Opened 2021-12-03 18:33 UTC by Ivan-Sizyh

2021-12-04 14:15 UTC, VidgarVii requested changes

2021-12-04 14:15 UTC, VidgarVii commented on Gemfile
> +gem 'i18n'
этот гем уже встроен в рельсу

2021-12-04 14:15 UTC, VidgarVii commented on README.md
> +  Test, Question, User, Test Administrator
как-то мало получилось сущностей )))

список сущностей приложения обычно выводится из сценария использования приложения

сценарий использования приложения примерно такой:
- Пользователь заходит на сайт
- он выбирает Тест
- Тест может принадлежать к одной из Категорий
- Тест состоит из Вопросов
- на каждый Вопрос есть несколько Ответов
- Пользователь выбирает один или несколько Ответов, чтобы ответить на каждый из Вопросов
- Результат тестирования сохраняется

2021-12-04 14:15 UTC, VidgarVii commented on README.md
> +  Test, Question, User, Test Administrator
А вот админ этот тот же юзер

2021-12-04 14:15 UTC, VidgarVii commented on config/application.rb
> +    config.active_record.default_timezone = :local
так делать не рекомендуется (`default_timezone = :local`)

стандарт - хранение времени в UTC
это намного удобнее для приложений, в которых используется несколько таймзон (приложение всегда может стать таким)

2021-12-04 14:15 UTC, VidgarVii commented on config/application.rb
> +    config.i18n.locale = :ru
достаточно config.i18n.default_locale
config.i18n.locale даже в документации нет
http://rusrails.ru/configuring-rails-applications#konfigurirovanie-i18n

2021-12-04 14:15 UTC, VidgarVii commented on config/initializers/assets.rb
> +Rails.application.config.assets.version = '0.1.0'
мне почему-то кажется, что ты не разобрался что это за конфигурация и что она делает
вот [документация](https://guides.rubyonrails.org/configuring.html#configuring-assets), вот на [SO](https://stackoverflow.com/questions/13873176/what-does-config-assets-version-do-in-rails) вопрос...

какое отношение конфигурация ассетов имеет к версии приложения?

2021-12-04 14:15 UTC, VidgarVii commented on config/locales/ru.yml
> +  Hello: "Привет мир!"
:+1:

2021-12-04 14:15 UTC, VidgarVii commented on config/initializers/assets.rb
> +Rails.application.config.assets.version = '0.1.0'
вот [посмотри](https://github.com/plataformatec/devise/blob/master/lib/devise/version.rb) как гем `Devise` хранит свою версию - это стандартный вариант для руби-гемов

а вот [пост](https://alexpeattie.com/blog/defining-versions-in-ruby-gems) про версификацию руби-гемов
посмотри на пример кода с патчем, где идет проверка версии `Devise`
удобно обращаться не просто ко вселенной - `VERSION`, а к конкретному модулю - `Devise::VERSION`
если вдруг код будет подразумевать необходимость использования версий нескольких модулей, то без неймспейсинга совсем не ясно, как разруливать ситуацию

2021-12-04 14:15 UTC, VidgarVii commented on public/about/about.html
> +  <p><a href="www.thinknetica.com/">Thinknetica</a></p>
ссылки на сторонние ресурсы правильно открывать в новой вкладке и хорошо бы добавить опцию rel=nofollow rel=noopener. Так клиента сохраним и поискового робота дальше не пустим

2021-12-04 14:15 UTC, VidgarVii commented on public/about/about.html
> +  <p><a href="author.html">Информация об авторе</a></p>
плохая идея делать отступы за счёт параграфов. Грубое нарушение семантики

2021-12-04 14:15 UTC, VidgarVii commented on public/about/about.html
> +<html lang="en">
не стыковка с языком. Ни же то текст на русском. А код говорит, что английский

2021-12-05 09:55 UTC, VidgarVii requested changes

2021-12-05 09:55 UTC, VidgarVii commented on Gemfile.lock
> +  i18n
запусти бандл

2021-12-05 09:55 UTC, VidgarVii commented on config/application.rb
> +    config.active_record.default_timezone = :utc
не надо вообще указывать default_timezone. Ты уже указываешь time_zone на 13 строке

2021-12-05 09:55 UTC, VidgarVii commented on config/initializers/version.rb
> +VERSION = "1.0.0".freeze
не стоит засорять глобальное пространство
версия относится к приложению, так что и константу нужно объявить в его контексте

посмотри к примеру в файл `config/application.rb` в какой модуль обернуто все твое приложение (9-я строка)

2021-12-05 09:55 UTC, VidgarVii commented on config/initializers/version.rb
> +VERSION = "1.0.0".freeze
ого мажорная версия??? а мы ведь еще ни чего не выкатывали в свет

2021-12-05 16:14 UTC, Ivan-Sizyh commented on config/application.rb
> +  VERSION = "0.1.0"
Или все же надо было создать модуль с версией в отдельном файле?

2021-12-06 07:34 UTC, VidgarVii requested changes

2021-12-06 07:34 UTC, VidgarVii commented on config/application.rb
> +  VERSION = "0.1.0".freeze
вы у друг друга списываете? Комментарий тот же, что у Сергея

2021-12-06 10:57 UTC, merged