Lesson 3 commit
Ivan-Sizyh/TestGuru pull request #3
Opened 2021-12-09 15:01 UTC by Ivan-Sizyh

2021-12-09 15:55 UTC, VidgarVii requested changes

2021-12-09 15:55 UTC, VidgarVii commented on app/models/test.rb
> +  end
Неплохой вариант, но через INNER JOIN будет читабельнее.

2021-12-09 15:55 UTC, VidgarVii commented on app/models/test.rb
> +    self.class.order(id: :desc).where(category: category_id).pluck(:title)
self.class
зачем все эти сложности.. Кстати а что вернёт этот self.class?!

2021-12-09 15:55 UTC, VidgarVii commented on app/models/test.rb
> +  end
запросы будет правильно решить через джойн таблиц
то как ты делаешь - это "решение в лоб"
оно работает, но оно скажем мягко "не оптимальное"

рельсы многие запросы могут сами оптимизировать в итоге и, к примеру, составить автоматически из двух запросов один, но полагаться на это не стоит
в реальной жизни такие запросы, как у тебя получились, писать не нужно

плюс мы сейчас пытаемся разобраться с тем, как работают ассоциации в рельсах, чтобы в дальнейшем было понимание того "что же они делают" и "как это работает", так вот рельсы точно не пишут такие запросы, конечно же все оптимизировано
посмотри предыдущее задание - там были (в части по скуль запросам) селекты с джойнами таблиц

здесь нужно в обоих методах решить все с помощью `joins` и `where` (в одно обращение к базе, один запрос)
пострайся разобраться - это важно и полезно

2021-12-09 15:55 UTC, VidgarVii commented on db/seeds.rb
> +answers = Answer.create([
лучше использовать `create!` - метод бросит исключение, если запись не создастся
сразу будет видно, если что-то пошло не так

2021-12-09 15:55 UTC, VidgarVii commented on db/seeds.rb
> +results = Result.create([
Если переменная не используется, то лучше её не создавать. Затрудняет работу сборщику мусора

2021-12-10 07:37 UTC, Ivan-Sizyh commented
https://github.com/Ivan-Sizyh/TestGuru/pull/3#issue-798912215

2021-12-15 06:22 UTC, VidgarVii commented on app/models/test.rb
> +  def self.give_tests_by_category(category)
Не удачное название для параметра метода. По названию параметра метода можно понять что надо передать сам объект категории. А по факту надо передать название категории.

2021-12-15 18:56 UTC, merged